apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:WpqHWOjtB9YmWpke6DUi8HhEH03zrwDtYQY=,iv:TKnsoYCyWibPPITmpodzAu6KYK8ltYATf4SHxUxBuf4=,tag:nj0KFmK/wdp09yyxeyaocw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:7A5EmYaoIANmRX5CUtELYfZYFofv2J6tgd/MV5VtJorkyWPvaA==,iv:W3AJhBUK/08kWrUGLvSJ2g6661x91abUv3KU20Js38c=,tag:d+Iwki/aMCP2eFLWUIHuaw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:xDWiOx9+bfcxsT6Fcg==,iv:HsgJBOuoNg7fciqgR9TuNKHRDvMnER7TD56py+FcPiQ=,tag:dQVeWgHIkazOXmVjegYWfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age184y6ftpeycg0m76rmdpa0ft58jywkgkac89ncq5ea7phcqda24kqgnv5l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORGNuNTI2aG9zT0U1QlBJ
            WmYvOCt6U2ZyeHY4M3diVk5VWHBPU0FzVTFnCkVVM0ZsR003dkpleHEvSC8wcWZT
            N1NaSCs4YjNId0U1ZktzSitOVW9mVVkKLS0tIEZiNENJREExWFFvYjBodk80Ly9X
            Vm5xeHNFWDZuZTIzZDl0WndHNEI2akUKggRSHnySPKRrjmtOjk6BJH2n7p4NN6Qb
            zpB7084gr3lEIkb2twu0z6KxZfSIJhUA97cfRe+s+ES3GdzWG3kINQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T21:24:37Z"
    mac: ENC[AES256_GCM,data:R/SOmgSolmkd7TwYPt0CTLE3sbIkZDgP0x8wDcnG8n45Qn2YrBThT8s+M7d9Mj8YC4Pq/SSK9qX6PLf8h7sFcix7KUY4vJQa2xeZ8nDFA9j915BcDio6+5nZA2XX0Ai3c3UM8LnzQB8cj+dvwwkB+8uk61TwUewEeZ84l4CQuxc=,iv:ogjcZVSRceyJhcU+9KG06pnBHK/Q21Hf/9uNRjch2us=,tag:88IxBuwQqorE9RY+RfKN/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
