---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: PersistentVolume
metadata:
  name: config-pv
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path:
      secretKeyRef:
        name: nfs-secrets
        key: config
    server:
      secretKeyRef:
        name: nfs-secrets
        key: ipaddress
