kind: ENC[AES256_GCM,data:aOB29nkt,iv:5WyLsohj09UvwrYiVD3Q/nQtsvUu+PNPI71zlB6xIzs=,tag:Y0q85Ht//JyATxVrk/9Gag==,type:str]
ansible_user: ENC[AES256_GCM,data:kYI77MXT,iv:GtsfwH/hDFOwlJR8JHXU4i+z8Emve+xwXr06xeLAqqY=,tag:Yc2vW+p9KY1NSJGPwJ6iHw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:/lsqbL0hMsYz,iv:WkyYOBJHoQoUmGvJFWZBPhlykzIFD7GbcY1yScu8BkY=,tag:JoOI5h/7fNHqwUdbTf1fPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age184y6ftpeycg0m76rmdpa0ft58jywkgkac89ncq5ea7phcqda24kqgnv5l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0R3daYzgva3k1SFlwY3Rp
            RUp1dWdBSGhwbUtwaXlEVXM2QWV5d25PcWpZCmN6aXFPQ3pmMlcwMXhobVplZ0U3
            WnlOSTU0UEVvaEpITGNPSkRYdzVjNTQKLS0tIHZaZ0d1R2hVdzBIc0ovVkdZTE1l
            MXdLMStsK0FtZ0dlVTlYS0U2aHRJTDgKDHSwwg4b0d3pbhFqVOfpwDUO3PmMJKfe
            W62Tw4qdyAWOvUhdvvic0qg52L3+rhyov16NDHahwAANgK4JSnKm3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-12T21:24:37Z"
    mac: ENC[AES256_GCM,data:onBAiBw4tDwvdChHYXRP/wfz/0Y51GankWG/nKnn74AN6B/k5NGvyc5CHWzcBQurjFBUc/HH1W4LkdruWhBiTdPSR4KmxGW8UGRZtWBOopLfGn1HOlyAQ3F2Uhzi8KtvqWn+hd6uLF/qKWxYLgmDothIX4ZQ0gIrEUG/XrYYVHE=,iv:hr6D/SRNzpbpXX2t8QKlvj1UflGqQ9JhvqpfkmPTKok=,tag:f2OKr05JiZqpEolVde46xA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
