apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:9yC/e7KgNgPuf9MFZ5mE+MSpkZ4U+VcXUYRM3D07uN9Juhw32w==,iv:8BjN+XsOp/zlJzIPOjwOP01Cwc510JFpDSTUWJ0YWYg=,tag:5h0u/e7lKZ3LrKzU1U3oGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age184y6ftpeycg0m76rmdpa0ft58jywkgkac89ncq5ea7phcqda24kqgnv5l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUjRZQlhsZ0pIODFBdmVB
            dzBlN2xDVElXTS9SU1E1Tk5sUUV3ME9RNDEwCkNUTjRkMXloSFZSU0RmRWJJUDJH
            KzVCdStldlhuUkZtN2lic0hFQ1VEZG8KLS0tIC9rUVFMUWhTZ05QazFvUlFhdXBz
            NVYwMXBGVzlPb1hzeFlzU21TVVF4VncK6YiHGHtFJoc/qeWVPJoepbg6vB13A7dz
            io8FE/jWhwTDL1xgqMIRenjkq/nfA0gdt9PWuMBubFxXcL5VDbMo+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-13T01:58:00Z"
    mac: ENC[AES256_GCM,data:5zF9Q5A24Z2u/vId+kfSGmoM831HURTE8WaeeNodIPxIsF9cVDe2LPxNKyg2j30ZJRpdpS5cQ7r/GrGYSDpquWqEd9TJ2khjilGCXIVT1NWtDoN7fItC5DG4PuW2hMRMkyBJ/lthW3mulWgnPbCxhQ10Ct2Ou9nniAJrtMswgMM=,iv:mgYPKb8mcS09mURkBmwkFCVr2HN+t9h9ZyppL2ir4Es=,tag:sx988QRPsJFRV/KvHez41w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
