---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Vancouver"
  KUBE_VIP_ADDR: "10.1.0.251"
  METALLB_LB_RANGE: "10.1.0.240-10.1.0.250"
  METALLB_K8S_GATEWAY_ADDR: "10.1.0.240"
  METALLB_INGRESS_ADDR: "10.1.0.241"
